apiVersion: v1
kind: Pod
metadata:
  name: new-pod
spec:
  containers: 
  - name: nginix
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: redis
    image: redis:latest
    ports:
    - containerPort: 6379